from array_list import ArrayList
from linked_list import DoublyLinkedList

def show_list(title, lst):
    print(f"{title} ({lst.length()}):", end=" ")
    for i in range(lst.length()):
        print(lst.get(i), end=" ")
    print()

print("=== ArrayList Demo ===")
arr = ArrayList()
arr.append('a')
arr.append('b')
arr.insert('x', 1)
show_list("After insert", arr)
arr.delete(0)
show_list("After delete", arr)
arr.append('b')
arr.append('b')
arr.deleteAll('b')
show_list("After deleteAll('b')", arr)
arr.append('c')
arr.append('d')
print("get(1):", arr.get(1))
print("findFirst('c'):", arr.findFirst('c'))
print("findLast('d'):", arr.findLast('d'))
arr.reverse()
show_list("After reverse", arr)
clone_arr = arr.clone()
show_list("Clone of arr", clone_arr)
arr.clear()
show_list("After clear", arr)

print("\n=== DoublyLinkedList Demo ===")
dll = DoublyLinkedList()
dll.append('a')
dll.append('b')
dll.insert('x', 1)
show_list("After insert", dll)
dll.delete(0)
show_list("After delete", dll)
dll.append('b')
dll.append('b')
dll.deleteAll('b')
show_list("After deleteAll('b')", dll)
dll.append('c')
dll.append('d')
print("get(1):", dll.get(1))
print("findFirst('c'):", dll.findFirst('c'))
print("findLast('d'):", dll.findLast('d'))
dll.reverse()
show_list("After reverse", dll)
clone_dll = dll.clone()
show_list("Clone of dll", clone_dll)
dll.clear()
show_list("After clear", dll)
